# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 954daaf9ea6bdead9d69f51a5f6900a2d793715b0c85006b636b8bb3ffdd12daa6d8555e9c5a7457a70f41a6ccd862c0260ae5b153febd198494c2d1404b66db
  facebook_app_id: 928084627261709
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: e14cdf2bdeb200e755207debb609ec3c9ddb8726df9d1a5b24682d8409927c9885e093d9ae628458ef543772af1f5d4864f5d33581c5ca065aea45fb74b1950c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 928084627261709
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
